### ISSUE TITLE
Error after run

### ISSUE THREAD

**Issue by Bu4ak** [firecow/gitlab-local-pipeline#2]
```bash
pkg/prelude/bootstrap.js:1261
      return wrapper.apply(this.exports, args);
                     ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Parser (/snapshot/gitlab-pipeline-local/dist/parser.js)
    at Object.<anonymous> (/snapshot/gitlab-pipeline-local/dist/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11

```

**Comment by firecow** [comment]
Ahaaaa... Can you provide med with your .gitlab-ci.yml or just the part of it that fails the parsing.

**Comment by Bu4ak** [comment]
```yml
image: php:5.6

services:
  - mysql:latest

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
      - .env

test:
  stage: test
  dependencies:
    - build
  script:
    - vendor/bin/codecept

```
